"""Add QuizQuestion model

Revision ID: ae5e4b74da1e
Revises: fe84e4ef1ceb
Create Date: 2024-10-27 19:54:35.826735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5e4b74da1e'
down_revision = 'fe84e4ef1ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('answer_a', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('answer_b', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('answer_c', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('answer_d', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('correct_answer_id', sa.Integer(), nullable=False))
        batch_op.drop_column('question')
        batch_op.drop_column('answer')
        batch_op.drop_column('options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('correct_answer_id')
        batch_op.drop_column('answer_d')
        batch_op.drop_column('answer_c')
        batch_op.drop_column('answer_b')
        batch_op.drop_column('answer_a')
        batch_op.drop_column('question_text')

    # ### end Alembic commands ###
